import * as cst from "@fst/cst"

export type Database = {
	timestamp_deliveryupdate: {
		id: number,
		timestamp_unix: number,
	},
	img_variant: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		area: number,
		filename: string,
		mimetype: string,
		img__id: string,
	},
	ping_device: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		token: string,
	},
	ping_msg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		phone: string,
		owner: string,
		status_checked: 0 | 1,
		cmethod: cst.PingMe_ContactMethod,
	},
	acc: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		access: number,
		status_sessional: 0 | 1,
		contact_email: string,
		contact_phone: string,
		contact_fname: string,
		contact_lname: string,
		contact_pname: string,
		delivery_division__id: string | null,
	},
	img: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
	},
	delivery_division: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		address: string,
		address_city: string,
		address_region: string,
		address_postcode: string,
		address_building: string,
		name_full: string,
		name_short: string,
		owner: string,
		source: string,
		category: string,
		latitude: number,
		longitude: number,
		numid: number,
		externalid: string,
		status_text: string,
		status_available: 0 | 1,
		parent_name: string,
		parent_numid: number,
		city_name: string,
		city_numid: number,
		country_code: string,
	},
	contact_message: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		topic: string,
		content: string,
		email: string,
		status_reviewed: 0 | 1,
		owner: string | null,
	},
	acc_authemail: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		email: string,
		password_hash: string,
		password_salt: string,
		owner: string,
	},
	tmplit: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	tmplit_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplit_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplit__id: string,
	},
	item: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
		tmplit__id: string,
	},
	item_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	item_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		item__id: string,
	},
	item_tag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	item_tag_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	item_reftag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		item__id: string,
		item_tag__id: string,
	},
	prodset: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
	},
	variant: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		header: string,
		description: string,
		status_hidden: 0 | 1,
		owner: string | null,
		prodset__id: string,
		item__id: string,
	},
	variant_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	tmplmt: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	tmplmt_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplmt_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplmt__id: string,
	},
	material: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		status_hidden: 0 | 1,
		status_available: 0 | 1,
		tmplmt__id: string,
	},
	material_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		material__id: string,
	},
	material_tag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	material_tag_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	material_reftag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		material__id: string,
		material_tag__id: string,
	},
	tmplpr: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		status_hidden: 0 | 1,
		price_formula: string,
		name: string,
	},
	tmplpr_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplpr__id: string,
	},
	tmplpr_arg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		hidden_formula: string,
		tmplpr__id: string,
		kind: cst.TmplPrArg_Kind,
	},
	tmplpr_arg_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_line: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value_def: number,
		x_bound_min: number,
		x_bound_max: number,
		x_value_step: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_line_mark: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		label: string,
		tmplpr_arg_line__id: string,
	},
	tmplpr_arg_line_mark_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_rect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value_def: number,
		x_bound_min: number,
		x_bound_max: number,
		x_value_step: number,
		y_value_def: number,
		y_bound_min: number,
		y_bound_max: number,
		y_value_step: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_rect_mark: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		label: string,
		tmplpr_arg_rect__id: string,
	},
	tmplpr_arg_rect_mark_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_bool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value_def: 0 | 1,
		title_true: string,
		title_false: string,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_bool_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_mat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_mat_perm: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		tmplmt__id: string | null,
		tmplpr_arg_mat__id: string,
	},
	product: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string | null,
		tmplpr__id: string,
		prodset__id: string,
	},
	product_argline: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		owner: string | null,
		product__id: string,
		tmplpr_arg_line__id: string,
	},
	product_argrect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		owner: string | null,
		product__id: string,
		tmplpr_arg_rect__id: string,
	},
	product_argmat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: string | null,
		owner: string | null,
		product__id: string,
		tmplpr_arg_mat__id: string,
	},
	product_argbool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: 0 | 1,
		owner: string | null,
		product__id: string,
		tmplpr_arg_bool__id: string,
	},
	cart_refnode: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string,
		commision_node__id: string,
	},
	commision: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		id_public: string,
		owner: string | null,
		status_static: 0 | 1,
		paynment_amount: number,
		status_delivered: 0 | 1,
		contact_email: string,
		contact_phone: string,
		contact_fname: string,
		contact_lname: string,
		contact_pname: string,
		delivery_division__id: string | null,
	},
	commision_refnode: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string | null,
		commision__id: string,
		commision_node__id: string,
	},
	commision_node: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		item_name: string,
		tmplit_name: string,
		variant_header: string,
		owner: string | null,
		item__id: string | null,
		tmplit__id: string | null,
		variant__id: string | null,
	},
	commision_node_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_node_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_node__id: string,
	},
	commision_product: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		price_formula: string,
		tmplpr_name: string,
		owner: string | null,
		tmplpr__id: string | null,
		commision_node__id: string,
	},
	commision_product_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_product__id: string,
	},
	commision_product_argline: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		name: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argline_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argrect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		name: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argrect_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argbool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: 0 | 1,
		name: string,
		title_true: string,
		title_false: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argbool_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argmat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		tmplmt_name: string,
		hidden_formula: string,
		owner: string | null,
		tmplmt__id: string | null,
		material__id: string | null,
		commision_product__id: string,
	},
	commision_product_argmat_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argmat_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_product_argmat__id: string,
	},
}

export type DatabasePublic = {
	ping_device: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		token: string,
	},
	ping_msg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		phone: string,
		owner: string,
		status_checked: 0 | 1,
		cmethod: cst.PingMe_ContactMethod,
	},
	acc: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		access: number,
		status_sessional: 0 | 1,
		contact_email: string,
		contact_phone: string,
		contact_fname: string,
		contact_lname: string,
		contact_pname: string,
		delivery_division__id: string | null,
	},
	img: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
	},
	delivery_division: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		address: string,
		address_city: string,
		address_region: string,
		address_postcode: string,
		address_building: string,
		name_full: string,
		name_short: string,
		owner: string,
		source: string,
		category: string,
		latitude: number,
		longitude: number,
		numid: number,
		externalid: string,
		status_text: string,
		status_available: 0 | 1,
		parent_name: string,
		parent_numid: number,
		city_name: string,
		city_numid: number,
		country_code: string,
	},
	contact_message: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		topic: string,
		content: string,
		email: string,
		status_reviewed: 0 | 1,
		owner: string | null,
	},
	acc_authemail: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		email: string,
		password_hash: string,
		password_salt: string,
		owner: string,
	},
	tmplit: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	tmplit_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplit_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplit__id: string,
	},
	item: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
		tmplit__id: string,
	},
	item_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	item_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		item__id: string,
	},
	item_tag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	item_tag_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	item_reftag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		item__id: string,
		item_tag__id: string,
	},
	prodset: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
	},
	variant: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		header: string,
		description: string,
		status_hidden: 0 | 1,
		owner: string | null,
		prodset__id: string,
		item__id: string,
	},
	variant_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	tmplmt: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	tmplmt_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplmt_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplmt__id: string,
	},
	material: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		status_hidden: 0 | 1,
		status_available: 0 | 1,
		tmplmt__id: string,
	},
	material_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		material__id: string,
	},
	material_tag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		status_hidden: 0 | 1,
	},
	material_tag_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	material_reftag: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		material__id: string,
		material_tag__id: string,
	},
	tmplpr: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		status_hidden: 0 | 1,
		price_formula: string,
		name: string,
	},
	tmplpr_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		img__id: string,
		tmplpr__id: string,
	},
	tmplpr_arg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		hidden_formula: string,
		tmplpr__id: string,
		kind: cst.TmplPrArg_Kind,
	},
	tmplpr_arg_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_line: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value_def: number,
		x_bound_min: number,
		x_bound_max: number,
		x_value_step: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_line_mark: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		label: string,
		tmplpr_arg_line__id: string,
	},
	tmplpr_arg_line_mark_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_rect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value_def: number,
		x_bound_min: number,
		x_bound_max: number,
		x_value_step: number,
		y_value_def: number,
		y_bound_min: number,
		y_bound_max: number,
		y_value_step: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_rect_mark: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		label: string,
		tmplpr_arg_rect__id: string,
	},
	tmplpr_arg_rect_mark_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_bool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value_def: 0 | 1,
		title_true: string,
		title_false: string,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_bool_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		source__id: string,
	},
	tmplpr_arg_mat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		tmplpr_arg__id: string,
	},
	tmplpr_arg_mat_perm: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		tmplmt__id: string | null,
		tmplpr_arg_mat__id: string,
	},
	product: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string | null,
		tmplpr__id: string,
		prodset__id: string,
	},
	product_argline: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		owner: string | null,
		product__id: string,
		tmplpr_arg_line__id: string,
	},
	product_argrect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		owner: string | null,
		product__id: string,
		tmplpr_arg_rect__id: string,
	},
	product_argmat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: string | null,
		owner: string | null,
		product__id: string,
		tmplpr_arg_mat__id: string,
	},
	product_argbool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: 0 | 1,
		owner: string | null,
		product__id: string,
		tmplpr_arg_bool__id: string,
	},
	cart_refnode: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string,
		commision_node__id: string,
	},
	commision: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		id_public: string,
		owner: string | null,
		status_static: 0 | 1,
		paynment_amount: number,
		status_delivered: 0 | 1,
		contact_email: string,
		contact_phone: string,
		contact_fname: string,
		contact_lname: string,
		contact_pname: string,
		delivery_division__id: string | null,
	},
	commision_refnode: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		owner: string | null,
		commision__id: string,
		commision_node__id: string,
	},
	commision_node: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		item_name: string,
		tmplit_name: string,
		variant_header: string,
		owner: string | null,
		item__id: string | null,
		tmplit__id: string | null,
		variant__id: string | null,
	},
	commision_node_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_node_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_node__id: string,
	},
	commision_product: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		quantity: number,
		price_formula: string,
		tmplpr_name: string,
		owner: string | null,
		tmplpr__id: string | null,
		commision_node__id: string,
	},
	commision_product_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_product__id: string,
	},
	commision_product_argline: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		name: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argline_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argrect: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		x_value: number,
		y_value: number,
		name: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argrect_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argbool: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		value: 0 | 1,
		name: string,
		title_true: string,
		title_false: string,
		hidden_formula: string,
		owner: string | null,
		commision_product__id: string,
	},
	commision_product_argbool_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argmat: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		name: string,
		tmplmt_name: string,
		hidden_formula: string,
		owner: string | null,
		tmplmt__id: string | null,
		material__id: string | null,
		commision_product__id: string,
	},
	commision_product_argmat_tl: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		lang: string,
		tltable: Record<string, string>,
		owner: string | null,
		source__id: string,
	},
	commision_product_argmat_refimg: {
		id: string,
		deleted: 0 | 1,
		creation_date: number,
		owner: string | null,
		img__id: string,
		commision_product_argmat__id: string,
	},
}