import * as cst from "@fst/cst"

export type RemDefImg = {
	img: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			url_raw: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				url_raw: string | null,
			},
		},
	},
}

export type RemDefData = {
	ping_device: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			token: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				token: string,
			},
		},
	},
	ping_msg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			phone: string,
			owner: string,
			status_checked: 0 | 1,
			cmethod: cst.PingMe_ContactMethod,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				phone: string,
				owner: string,
				status_checked: 0 | 1,
				cmethod: cst.PingMe_ContactMethod,
			},
		},
	},
	acc: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			access: number,
			status_sessional: 0 | 1,
			contact_email: string,
			contact_phone: string,
			contact_fname: string,
			contact_lname: string,
			contact_pname: string,
			delivery_division__id: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				access: number,
				status_sessional: 0 | 1,
				contact_email: string,
				contact_phone: string,
				contact_fname: string,
				contact_lname: string,
				contact_pname: string,
				delivery_division__id: string | null,
			},
		},
	},
	delivery_division: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			address: string,
			address_city: string,
			address_region: string,
			address_postcode: string,
			address_building: string,
			name_full: string,
			name_short: string,
			owner: string,
			source: string,
			category: string,
			latitude: number,
			longitude: number,
			numid: number,
			externalid: string,
			status_text: string,
			status_available: 0 | 1,
			parent_name: string,
			parent_numid: number,
			city_name: string,
			city_numid: number,
			country_code: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				address: string,
				address_city: string,
				address_region: string,
				address_postcode: string,
				address_building: string,
				name_full: string,
				name_short: string,
				owner: string,
				source: string,
				category: string,
				latitude: number,
				longitude: number,
				numid: number,
				externalid: string,
				status_text: string,
				status_available: 0 | 1,
				parent_name: string,
				parent_numid: number,
				city_name: string,
				city_numid: number,
				country_code: string,
			},
		},
	},
	contact_message: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			topic: string,
			content: string,
			email: string,
			status_reviewed: 0 | 1,
			owner: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				topic: string,
				content: string,
				email: string,
				status_reviewed: 0 | 1,
				owner: string | null,
			},
		},
	},
	acc_authemail: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			email: string,
			owner: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				email: string,
				owner: string,
			},
		},
	},
	tmplit: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			status_hidden: 0 | 1,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				status_hidden: 0 | 1,
				tl: (RemDef["tmplit_tl"]["joins"]["core"])[],
				refimgs: (RemDef["tmplit_refimg"]["joins"]["core"])[],
			},
		},
	},
	tmplit_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplit_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			img__id: string,
			tmplit__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				img__id: string,
				tmplit__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	item: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			status_hidden: 0 | 1,
			tmplit__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				status_hidden: 0 | 1,
				tmplit__id: string,
				tl: (RemDef["item_tl"]["joins"]["core"])[],
				variants: (RemDef["variant"]["joins"]["core"])[],
				template: RemDef["tmplit"]["joins"]["core"],
				refimgs: (RemDef["item_refimg"]["joins"]["core"])[],
				reftags: (RemDef["item_reftag"]["joins"]["core"])[],
			},
		},
	},
	item_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	item_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			img__id: string,
			item__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				img__id: string,
				item__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	item_tag: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			status_hidden: 0 | 1,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				status_hidden: 0 | 1,
				tl: (RemDef["item_tag_tl"]["joins"]["core"])[],
			},
		},
	},
	item_tag_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	item_reftag: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			item__id: string,
			item_tag__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				item__id: string,
				item_tag__id: string,
				tag: RemDef["item_tag"]["joins"]["core"],
			},
		},
	},
	prodset: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			owner: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				owner: string | null,
				products: (RemDef["product"]["joins"]["core"])[],
			},
		},
	},
	variant: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			header: string,
			description: string,
			status_hidden: 0 | 1,
			owner: string | null,
			prodset__id: string,
			item__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				header: string,
				description: string,
				status_hidden: 0 | 1,
				owner: string | null,
				prodset__id: string,
				item__id: string,
				prodset: RemDef["prodset"]["joins"]["core"],
				tl: (RemDef["variant_tl"]["joins"]["core"])[],
			},
		},
	},
	variant_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	tmplmt: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			status_hidden: 0 | 1,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				status_hidden: 0 | 1,
				tl: (RemDef["tmplmt_tl"]["joins"]["core"])[],
				refimgs: (RemDef["tmplmt_refimg"]["joins"]["core"])[],
			},
		},
	},
	tmplmt_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplmt_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			img__id: string,
			tmplmt__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				img__id: string,
				tmplmt__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	material: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			status_hidden: 0 | 1,
			status_available: 0 | 1,
			tmplmt__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				status_hidden: 0 | 1,
				status_available: 0 | 1,
				tmplmt__id: string,
				template: RemDef["tmplmt"]["joins"]["core"],
				reftags: (RemDef["material_reftag"]["joins"]["core"])[],
				refimgs: (RemDef["material_refimg"]["joins"]["core"])[],
			},
		},
	},
	material_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			img__id: string,
			material__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				img__id: string,
				material__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	material_tag: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			status_hidden: 0 | 1,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				status_hidden: 0 | 1,
				tl: (RemDef["material_tag_tl"]["joins"]["core"])[],
			},
		},
	},
	material_tag_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	material_reftag: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			material__id: string,
			material_tag__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				material__id: string,
				material_tag__id: string,
				tag: RemDef["material_tag"]["joins"]["core"],
			},
		},
	},
	tmplpr: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			status_hidden: 0 | 1,
			price_formula: string,
			name: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				status_hidden: 0 | 1,
				price_formula: string,
				name: string,
				tl: (RemDef["tmplpr_tl"]["joins"]["core"])[],
				args: (RemDef["tmplpr_arg"]["joins"]["core"])[],
				refimgs: (RemDef["tmplpr_refimg"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplpr_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			img__id: string,
			tmplpr__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				img__id: string,
				tmplpr__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	tmplpr_arg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			hidden_formula: string,
			tmplpr__id: string,
			kind: cst.TmplPrArg_Kind,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				hidden_formula: string,
				tmplpr__id: string,
				kind: cst.TmplPrArg_Kind,
				tl: (RemDef["tmplpr_arg_tl"]["joins"]["core"])[],
				defs_mat: (RemDef["tmplpr_arg_mat"]["joins"]["core"])[],
				defs_line: (RemDef["tmplpr_arg_line"]["joins"]["core"])[],
				defs_rect: (RemDef["tmplpr_arg_rect"]["joins"]["core"])[],
				defs_bool: (RemDef["tmplpr_arg_bool"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplpr_arg_line: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value_def: number,
			x_bound_min: number,
			x_bound_max: number,
			x_value_step: number,
			tmplpr_arg__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value_def: number,
				x_bound_min: number,
				x_bound_max: number,
				x_value_step: number,
				tmplpr_arg__id: string,
				marks: (RemDef["tmplpr_arg_line_mark"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_line_mark: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			label: string,
			tmplpr_arg_line__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				label: string,
				tmplpr_arg_line__id: string,
				tl: (RemDef["tmplpr_arg_line_mark_tl"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_line_mark_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplpr_arg_rect: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value_def: number,
			x_bound_min: number,
			x_bound_max: number,
			x_value_step: number,
			y_value_def: number,
			y_bound_min: number,
			y_bound_max: number,
			y_value_step: number,
			tmplpr_arg__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value_def: number,
				x_bound_min: number,
				x_bound_max: number,
				x_value_step: number,
				y_value_def: number,
				y_bound_min: number,
				y_bound_max: number,
				y_value_step: number,
				tmplpr_arg__id: string,
				marks: (RemDef["tmplpr_arg_rect_mark"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_rect_mark: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			y_value: number,
			label: string,
			tmplpr_arg_rect__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				y_value: number,
				label: string,
				tmplpr_arg_rect__id: string,
				tl: (RemDef["tmplpr_arg_rect_mark_tl"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_rect_mark_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplpr_arg_bool: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			value_def: 0 | 1,
			title_true: string,
			title_false: string,
			tmplpr_arg__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				value_def: 0 | 1,
				title_true: string,
				title_false: string,
				tmplpr_arg__id: string,
				tl: (RemDef["tmplpr_arg_bool_tl"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_bool_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				source__id: string,
			},
		},
	},
	tmplpr_arg_mat: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			tmplpr_arg__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				tmplpr_arg__id: string,
				perms: (RemDef["tmplpr_arg_mat_perm"]["joins"]["core"])[],
			},
		},
	},
	tmplpr_arg_mat_perm: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			tmplmt__id: string | null,
			tmplpr_arg_mat__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				tmplmt__id: string | null,
				tmplpr_arg_mat__id: string,
				template: RemDef["tmplmt"]["joins"]["core"],
			},
		},
	},
	product: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			quantity: number,
			owner: string | null,
			tmplpr__id: string,
			prodset__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				quantity: number,
				owner: string | null,
				tmplpr__id: string,
				prodset__id: string,
				template: RemDef["tmplpr"]["joins"]["core"],
				argimps_line: (RemDef["product_argline"]["joins"]["core"])[],
				argimps_rect: (RemDef["product_argrect"]["joins"]["core"])[],
				argimps_mat: (RemDef["product_argmat"]["joins"]["core"])[],
				argimps_bool: (RemDef["product_argbool"]["joins"]["core"])[],
			},
		},
	},
	product_argline: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			owner: string | null,
			product__id: string,
			tmplpr_arg_line__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				owner: string | null,
				product__id: string,
				tmplpr_arg_line__id: string,
			},
		},
	},
	product_argrect: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			y_value: number,
			owner: string | null,
			product__id: string,
			tmplpr_arg_rect__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				y_value: number,
				owner: string | null,
				product__id: string,
				tmplpr_arg_rect__id: string,
			},
		},
	},
	product_argmat: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			value: string | null,
			owner: string | null,
			product__id: string,
			tmplpr_arg_mat__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				value: RemDef["material"]["joins"]["core"] | undefined,
				owner: string | null,
				product__id: string,
				tmplpr_arg_mat__id: string,
			},
		},
	},
	product_argbool: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			value: 0 | 1,
			owner: string | null,
			product__id: string,
			tmplpr_arg_bool__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				value: 0 | 1,
				owner: string | null,
				product__id: string,
				tmplpr_arg_bool__id: string,
			},
		},
	},
	cart_refnode: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			quantity: number,
			owner: string,
			commision_node__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				quantity: number,
				owner: string,
				commision_node__id: string,
				node: RemDef["commision_node"]["joins"]["core"],
			},
		},
	},
	commision: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			id_public: string,
			owner: string | null,
			status_static: 0 | 1,
			paynment_amount: number,
			status_delivered: 0 | 1,
			contact_email: string,
			contact_phone: string,
			contact_fname: string,
			contact_lname: string,
			contact_pname: string,
			delivery_division__id: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				id_public: string,
				owner: string | null,
				status_static: 0 | 1,
				paynment_amount: number,
				status_delivered: 0 | 1,
				contact_email: string,
				contact_phone: string,
				contact_fname: string,
				contact_lname: string,
				contact_pname: string,
				delivery_division__id: string | null,
				refnodes: (RemDef["commision_refnode"]["joins"]["core"])[],
				delivery_division: RemDef["delivery_division"]["joins"]["core"] | undefined,
			},
		},
	},
	commision_refnode: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			quantity: number,
			owner: string | null,
			commision__id: string,
			commision_node__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				quantity: number,
				owner: string | null,
				commision__id: string,
				commision_node__id: string,
				node: RemDef["commision_node"]["joins"]["core"],
			},
		},
	},
	commision_node: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			item_name: string,
			tmplit_name: string,
			variant_header: string,
			owner: string | null,
			item__id: string | null,
			tmplit__id: string | null,
			variant__id: string | null,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				item_name: string,
				tmplit_name: string,
				variant_header: string,
				owner: string | null,
				item__id: string | null,
				tmplit__id: string | null,
				variant__id: string | null,
				tl: (RemDef["commision_node_tl"]["joins"]["core"])[],
				refimgs: (RemDef["commision_node_refimg"]["joins"]["core"])[],
				products: (RemDef["commision_product"]["joins"]["core"])[],
			},
		},
	},
	commision_node_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_node_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			owner: string | null,
			img__id: string,
			commision_node__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				owner: string | null,
				img__id: string,
				commision_node__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	commision_product: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			quantity: number,
			price_formula: string,
			tmplpr_name: string,
			owner: string | null,
			tmplpr__id: string | null,
			commision_node__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				quantity: number,
				price_formula: string,
				tmplpr_name: string,
				owner: string | null,
				tmplpr__id: string | null,
				commision_node__id: string,
				tl: (RemDef["commision_product_tl"]["joins"]["core"])[],
				refimgs: (RemDef["commision_product_refimg"]["joins"]["core"])[],
				args_line: (RemDef["commision_product_argline"]["joins"]["core"])[],
				args_rect: (RemDef["commision_product_argrect"]["joins"]["core"])[],
				args_bool: (RemDef["commision_product_argbool"]["joins"]["core"])[],
				args_mat: (RemDef["commision_product_argmat"]["joins"]["core"])[],
			},
		},
	},
	commision_product_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_product_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			owner: string | null,
			img__id: string,
			commision_product__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				owner: string | null,
				img__id: string,
				commision_product__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
	commision_product_argline: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			name: string,
			hidden_formula: string,
			owner: string | null,
			commision_product__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				name: string,
				hidden_formula: string,
				owner: string | null,
				commision_product__id: string,
				tl: (RemDef["commision_product_argline_tl"]["joins"]["core"])[],
			},
		},
	},
	commision_product_argline_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_product_argrect: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			x_value: number,
			y_value: number,
			name: string,
			hidden_formula: string,
			owner: string | null,
			commision_product__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				x_value: number,
				y_value: number,
				name: string,
				hidden_formula: string,
				owner: string | null,
				commision_product__id: string,
				tl: (RemDef["commision_product_argrect_tl"]["joins"]["core"])[],
			},
		},
	},
	commision_product_argrect_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_product_argbool: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			value: 0 | 1,
			name: string,
			title_true: string,
			title_false: string,
			hidden_formula: string,
			owner: string | null,
			commision_product__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				value: 0 | 1,
				name: string,
				title_true: string,
				title_false: string,
				hidden_formula: string,
				owner: string | null,
				commision_product__id: string,
				tl: (RemDef["commision_product_argbool_tl"]["joins"]["core"])[],
			},
		},
	},
	commision_product_argbool_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_product_argmat: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			name: string,
			tmplmt_name: string,
			hidden_formula: string,
			owner: string | null,
			tmplmt__id: string | null,
			material__id: string | null,
			commision_product__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				name: string,
				tmplmt_name: string,
				hidden_formula: string,
				owner: string | null,
				tmplmt__id: string | null,
				material__id: string | null,
				commision_product__id: string,
				tl: (RemDef["commision_product_argmat_tl"]["joins"]["core"])[],
				tmplmt: RemDef["tmplmt"]["joins"]["core"] | undefined,
				material: RemDef["material"]["joins"]["core"] | undefined,
				refimgs: (RemDef["commision_product_argmat_refimg"]["joins"]["core"])[],
			},
		},
	},
	commision_product_argmat_tl: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			lang: string,
			tltable: Record<string, string>,
			owner: string | null,
			source__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				lang: string,
				tltable: Record<string, string>,
				owner: string | null,
				source__id: string,
			},
		},
	},
	commision_product_argmat_refimg: {
		data: {
			id: string,
			deleted: 0 | 1,
			creation_date: number,
			owner: string | null,
			img__id: string,
			commision_product_argmat__id: string,
		},
		joins: {
			core: {
				id: string,
				deleted: 0 | 1,
				creation_date: number,
				owner: string | null,
				img__id: string,
				commision_product_argmat__id: string,
				img: RemDef["img"]["joins"]["core"],
			},
		},
	},
}

export type RemDef = (RemDefImg & RemDefData)